CREATE TYPE "ManualDownloadMode" AS ENUM ('ARR_MANAGED', 'QBIT_REVIEWED');

ALTER TYPE "ManualDownloadStatus" ADD VALUE 'PREFLIGHT';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'CREATING_MEDIA';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'SUBMITTING_RELEASE';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'QUEUED';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'IMPORT_PENDING';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'NEEDS_MAPPING';
ALTER TYPE "ManualDownloadStatus" ADD VALUE 'BLOCKED';
