ALTER TABLE "AppSettings"
  ADD COLUMN "timeZone" TEXT NOT NULL DEFAULT 'UTC',
  ADD COLUMN "logLevel" TEXT NOT NULL DEFAULT 'debug',
  ADD COLUMN "logMaxFileMb" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "logRetentionDays" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN "logClientConsoleEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "logFailedRequestBodies" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "logFailedResponseBodies" BOOLEAN NOT NULL DEFAULT true;
