-- -- CreateTable
-- CREATE TABLE "ScheduledAlert" (
--     "id" TEXT NOT NULL,
--     "userId" TEXT NOT NULL,
--     "source" TEXT NOT NULL,
--     "externalId" TEXT NOT NULL,
--     "mediaType" TEXT NOT NULL,
--     "instanceId" TEXT,
--     "title" TEXT NOT NULL,
--     "subtitle" TEXT,
--     "posterUrl" TEXT,
--     "href" TEXT,
--     "scheduleMode" TEXT NOT NULL,
--     "scope" TEXT NOT NULL,
--     "releaseTypes" JSONB NOT NULL DEFAULT '[]',
--     "offsetMinutes" INTEGER NOT NULL DEFAULT 0,
--     "timeZone" TEXT NOT NULL DEFAULT 'UTC',
--     "status" TEXT NOT NULL DEFAULT 'active',
--     "metadata" JSONB,
--     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     "updatedAt" TIMESTAMP(3) NOT NULL,
--     "cancelledAt" TIMESTAMP(3),

--     CONSTRAINT "ScheduledAlert_pkey" PRIMARY KEY ("id")
-- );

-- -- CreateTable
-- CREATE TABLE "ScheduledAlertOccurrence" (
--     "id" TEXT NOT NULL,
--     "alertId" TEXT NOT NULL,
--     "releaseAt" TIMESTAMP(3),
--     "notifyAt" TIMESTAMP(3) NOT NULL,
--     "releaseKind" TEXT NOT NULL,
--     "targetKey" TEXT NOT NULL,
--     "title" TEXT NOT NULL,
--     "body" TEXT,
--     "metadata" JSONB,
--     "status" TEXT NOT NULL DEFAULT 'pending',
--     "attempts" INTEGER NOT NULL DEFAULT 0,
--     "lastAttemptAt" TIMESTAMP(3),
--     "sentAt" TIMESTAMP(3),
--     "cancelledAt" TIMESTAMP(3),
--     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     "updatedAt" TIMESTAMP(3) NOT NULL,

--     CONSTRAINT "ScheduledAlertOccurrence_pkey" PRIMARY KEY ("id")
-- );

-- -- CreateIndex
-- CREATE INDEX "ScheduledAlert_userId_status_createdAt_idx" ON "ScheduledAlert"("userId", "status", "createdAt");

-- -- CreateIndex
-- CREATE INDEX "ScheduledAlert_userId_source_externalId_mediaType_idx" ON "ScheduledAlert"("userId", "source", "externalId", "mediaType");

-- -- CreateIndex
-- CREATE INDEX "ScheduledAlertOccurrence_status_notifyAt_idx" ON "ScheduledAlertOccurrence"("status", "notifyAt");

-- -- CreateIndex
-- CREATE INDEX "ScheduledAlertOccurrence_alertId_status_notifyAt_idx" ON "ScheduledAlertOccurrence"("alertId", "status", "notifyAt");

-- -- CreateIndex
-- CREATE UNIQUE INDEX "ScheduledAlertOccurrence_alertId_targetKey_notifyAt_key" ON "ScheduledAlertOccurrence"("alertId", "targetKey", "notifyAt");

-- -- AddForeignKey
-- -- The checked-in migration history predates the current User/Watchlist schema in
-- -- some installs. Keep shadow-database replay valid while adding the FK on real
-- -- databases that already have the User table.
-- DO $$
-- BEGIN
--   IF to_regclass('"User"') IS NOT NULL THEN
--     ALTER TABLE "ScheduledAlert"
--       ADD CONSTRAINT "ScheduledAlert_userId_fkey"
--       FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
--   END IF;
-- END $$;

-- -- AddForeignKey
-- ALTER TABLE "ScheduledAlertOccurrence" ADD CONSTRAINT "ScheduledAlertOccurrence_alertId_fkey" FOREIGN KEY ("alertId") REFERENCES "ScheduledAlert"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- -- Backfill watchlist reminders into the new scheduler tables.
-- DO $$
-- BEGIN
--   IF to_regclass('"WatchlistItem"') IS NOT NULL
--     AND EXISTS (
--       SELECT 1 FROM information_schema.columns
--       WHERE table_schema = current_schema()
--         AND table_name = 'WatchlistItem'
--         AND column_name = 'userId'
--     )
--     AND EXISTS (
--       SELECT 1 FROM information_schema.columns
--       WHERE table_schema = current_schema()
--         AND table_name = 'WatchlistItem'
--         AND column_name = 'reminderAt'
--     )
--   THEN
--     INSERT INTO "ScheduledAlert" (
--         "id",
--         "userId",
--         "source",
--         "externalId",
--         "mediaType",
--         "title",
--         "subtitle",
--         "posterUrl",
--         "href",
--         "scheduleMode",
--         "scope",
--         "releaseTypes",
--         "offsetMinutes",
--         "timeZone",
--         "status",
--         "metadata",
--         "createdAt",
--         "updatedAt"
--     )
--     SELECT
--         'migrated-wl-' || w."id" AS "id",
--         w."userId",
--         w."source",
--         w."externalId",
--         w."mediaType",
--         w."title",
--         NULL AS "subtitle",
--         w."posterUrl",
--         CASE
--             WHEN w."source" = 'ANILIST' THEN '/anime/' || w."externalId"
--             WHEN w."source" = 'SONARR' THEN '/series/' || w."externalId"
--             WHEN w."source" = 'RADARR' THEN '/movies/' || w."externalId"
--             WHEN w."source" = 'TMDB' AND w."mediaType" = 'movie' THEN '/discover/movie/' || w."externalId"
--             WHEN w."source" = 'TMDB' AND w."mediaType" = 'series' THEN '/discover/tv/' || w."externalId"
--             ELSE NULL
--         END AS "href",
--         'absolute' AS "scheduleMode",
--         CASE
--             WHEN w."mediaType" = 'movie' THEN 'movie'
--             WHEN w."mediaType" = 'anime' THEN 'anime'
--             ELSE 'series'
--         END AS "scope",
--         '[]'::jsonb AS "releaseTypes",
--         0 AS "offsetMinutes",
--         'UTC' AS "timeZone",
--         CASE WHEN w."reminderNotifiedAt" IS NOT NULL THEN 'cancelled' ELSE 'active' END AS "status",
--         jsonb_build_object('migratedFromWatchlist', true, 'watchlistItemId', w."id") AS "metadata",
--         w."addedAt" AS "createdAt",
--         CURRENT_TIMESTAMP AS "updatedAt"
--     FROM "WatchlistItem" w
--     WHERE w."reminderAt" IS NOT NULL
--       AND w."userId" IS NOT NULL
--     ON CONFLICT ("id") DO NOTHING;

--     INSERT INTO "ScheduledAlertOccurrence" (
--         "id",
--         "alertId",
--         "releaseAt",
--         "notifyAt",
--         "releaseKind",
--         "targetKey",
--         "title",
--         "body",
--         "status",
--         "attempts",
--         "sentAt",
--         "createdAt",
--         "updatedAt"
--     )
--     SELECT
--         'migrated-wl-occ-' || w."id" AS "id",
--         'migrated-wl-' || w."id" AS "alertId",
--         w."reminderAt" AS "releaseAt",
--         w."reminderAt" AS "notifyAt",
--         'custom' AS "releaseKind",
--         'watchlist:' || w."id" AS "targetKey",
--         w."title" AS "title",
--         CASE WHEN w."year" IS NOT NULL THEN w."title" || ' (' || w."year"::text || ')' ELSE w."title" END AS "body",
--         CASE
--             WHEN w."reminderNotifiedAt" IS NOT NULL THEN 'sent'
--             WHEN w."reminderAt" < CURRENT_TIMESTAMP THEN 'failed'
--             ELSE 'pending'
--         END AS "status",
--         w."reminderAttempts" AS "attempts",
--         w."reminderNotifiedAt" AS "sentAt",
--         w."addedAt" AS "createdAt",
--         CURRENT_TIMESTAMP AS "updatedAt"
--     FROM "WatchlistItem" w
--     WHERE w."reminderAt" IS NOT NULL
--       AND w."userId" IS NOT NULL
--     ON CONFLICT ("id") DO NOTHING;
--   END IF;
-- END $$;

-- -- Seed scheduledAlert notification preferences for existing subscriptions.
-- DO $$
-- BEGIN
--   IF to_regclass('"PushSubscription"') IS NOT NULL
--     AND to_regclass('"NotificationPreference"') IS NOT NULL
--   THEN
--     IF EXISTS (
--       SELECT 1 FROM information_schema.columns
--       WHERE table_schema = current_schema()
--         AND table_name = 'PushSubscription'
--         AND column_name = 'revokedAt'
--     ) THEN
--       INSERT INTO "NotificationPreference" (
--           "id",
--           "subscriptionId",
--           "eventType",
--           "enabled",
--           "createdAt",
--           "updatedAt"
--       )
--       SELECT
--           'pref-backfill-' || s."id" || '-scheduledAlert' AS "id",
--           s."id" AS "subscriptionId",
--           'scheduledAlert' AS "eventType",
--           true AS "enabled",
--           CURRENT_TIMESTAMP AS "createdAt",
--           CURRENT_TIMESTAMP AS "updatedAt"
--       FROM "PushSubscription" s
--       WHERE s."revokedAt" IS NULL
--       ON CONFLICT ("subscriptionId", "eventType") DO NOTHING;
--     ELSE
--       INSERT INTO "NotificationPreference" (
--           "id",
--           "subscriptionId",
--           "eventType",
--           "enabled",
--           "createdAt",
--           "updatedAt"
--       )
--       SELECT
--           'pref-backfill-' || s."id" || '-scheduledAlert' AS "id",
--           s."id" AS "subscriptionId",
--           'scheduledAlert' AS "eventType",
--           true AS "enabled",
--           CURRENT_TIMESTAMP AS "createdAt",
--           CURRENT_TIMESTAMP AS "updatedAt"
--       FROM "PushSubscription" s
--       ON CONFLICT ("subscriptionId", "eventType") DO NOTHING;
--     END IF;
--   END IF;
-- END $$;
